version: '3'

services:
  my-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      my-db:
        condition: service_healthy
  my-db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: mydb
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p123456"]
      interval: 5s
      retries: 10